### ISSUE TITLE
希望可以设置图片的类别或搜索图片的关键字

### ISSUE THREAD

**Issue by walkinger** [shansb/unsplash4deepin-qt#1]
希望可以设置图片的类别或搜索图片的关键字

**Comment by shansb** [comment]
现在我采用的是https://source.unsplash.com/ 提供的无限制API。要实现搜索功能就得使用unsplash的开发者API。初级的应用只有50个请求/每小时，我觉得会挂。如果让大家自己申请一个API我觉得成本又太高。如果哪天找到有效好用的API我会第一时间更新。

**Comment by shansb** [comment]
因为api更新，针对unsplash已添加一些常见的类别，也可以自己去`~/.config/unplash4deepin/setting.ini`里设置keyword，关键字之间用逗号隔开，例如 `Keyword=water, nature`
